# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSpice < Formula
  desc "A tool for stacking Git branches."
  homepage "https://abhinav.github.io/git-spice/"
  version "0.1.0"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/abhinav/git-spice/releases/download/v0.1.0/git-spice.Darwin-x86_64.tar.gz"
      sha256 "3d4a549311cadf3986f94ffa50d2dedaeb693cfe8181c502926c6e30ad2d1888"

      def install
        bin.install "gs"
      end
    end
    on_arm do
      url "https://github.com/abhinav/git-spice/releases/download/v0.1.0/git-spice.Darwin-arm64.tar.gz"
      sha256 "852dbda137f00d94d06156bf203bf7470a4d088557fbcae1b35888a91fd6792d"

      def install
        bin.install "gs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abhinav/git-spice/releases/download/v0.1.0/git-spice.Linux-x86_64.tar.gz"
        sha256 "837f88ea5d5e48043759dd1bbf9d6e016153bcbc8e06aa4463e815710d707560"

        def install
          bin.install "gs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abhinav/git-spice/releases/download/v0.1.0/git-spice.Linux-aarch64.tar.gz"
        sha256 "cf22ccb07ed6a26172a0d944feaa796c5a66d7cfa7fb7d2501fc3bece383fedd"

        def install
          bin.install "gs"
        end
      end
    end
  end

  test do
    system "#{bin}/gs --version"
  end
end
