# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSpice < Formula
  desc "A tool for stacking Git branches."
  homepage "https://abhinav.github.io/git-spice/"
  version "0.14.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.0/git-spice.Darwin-x86_64.tar.gz"
      sha256 "3961a63f58b7655ecfb4ae0ccd2a6747c704a161fd7fba6a628e9777dd348658"

      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.0/git-spice.Darwin-arm64.tar.gz"
      sha256 "ba18c4c5f20bbcc734f7e02a5c601e0f4ccf3e8e7af064f7e910d151d6ce98c8"

      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.0/git-spice.Linux-x86_64.tar.gz"
      sha256 "c3476407316eec39ca3605903208b9988e730ef5eceee224a13d9a1e936d0ce5"
      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.0/git-spice.Linux-armv6.tar.gz"
      sha256 "c5fa6d1c0def3fc17bcc836c3161bb832dafc598a56c794d63229b659e5ee9f4"
      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.0/git-spice.Linux-aarch64.tar.gz"
      sha256 "82a55a3144705b4ffd3d947ec21ce86de1ae4c5fb732aba548e8cf1098257b83"
      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
  end

  test do
    system "#{bin}/gs --version"
  end
end
