# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSpice < Formula
  desc "A tool for stacking Git branches."
  homepage "https://abhinav.github.io/git-spice/"
  version "0.14.1"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.1/git-spice.Darwin-x86_64.tar.gz"
      sha256 "c41410f0d1b5b5fb33ac47ecd26a722cbb2aa109758898eff19bcb4055bb4124"

      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.1/git-spice.Darwin-arm64.tar.gz"
      sha256 "b52427045bf118b518a4d1ddf2f160e9271f6f0560a39a81fb5805f983a7c34c"

      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.1/git-spice.Linux-x86_64.tar.gz"
      sha256 "2d13c89ee42c8f7ec3fab4065653b6d412ccbcd4cc1dc57530ac62f44f8b8c62"
      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.1/git-spice.Linux-armv6.tar.gz"
      sha256 "073f9366d37d936d3fe50777840f8ece4a675fca77c6c74e4f41fd1619d6936d"
      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/git-spice/releases/download/v0.14.1/git-spice.Linux-aarch64.tar.gz"
      sha256 "25d06611dd77a6ac4a08f64c6e0c6ed47cdb12bc1491abc81bc916c886524f5c"
      def install
        bin.install "gs"
        generate_completions_from_executable(bin/"gs", "shell", "completion")
      end
    end
  end

  test do
    system "#{bin}/gs --version"
  end
end
