# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitprompt < Formula
  desc " Informative git prompt for zsh and bash"
  homepage "https://github.com/abhinav/gitprompt"
  version "0.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/gitprompt/releases/download/v0.8.1/gitprompt_0.8.1_Darwin_x86_64.tar.gz"
      sha256 "bdfefae52ee699b41a51cb08a331d185c84a66e7f4e42d963927ae1dbfd07af1"

      def install
        bin.install "gitprompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/gitprompt/releases/download/v0.8.1/gitprompt_0.8.1_Darwin_arm64.tar.gz"
      sha256 "653145fb5d9557aab28626c2eed651623f75f14e338fcd2b558854e4cd8d865f"

      def install
        bin.install "gitprompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/gitprompt/releases/download/v0.8.1/gitprompt_0.8.1_Linux_arm64.tar.gz"
      sha256 "57a32f07ec622256acd7eaa954c3c531786a5dd5d76799a55d9272b2ed663171"

      def install
        bin.install "gitprompt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/gitprompt/releases/download/v0.8.1/gitprompt_0.8.1_Linux_x86_64.tar.gz"
      sha256 "94a690c9f691b99f32f7639485da47f080ee1d5f2e6416a7e3be33806aa1fd1c"

      def install
        bin.install "gitprompt"
      end
    end
  end

  depends_on "git"
end
