# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restack < Formula
  desc "Makes interactive Git rebase nicer."
  homepage "https://github.com/abhinav/restack"
  version "0.5.4"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/restack/releases/download/v0.5.4/restack_0.5.4_Darwin_x86_64.tar.gz"
      sha256 "cbd643754b57d5d82b8fe3e609ff5f4ec1e2b0ec3ca70804e2032b2eb60ec979"

      def install
        bin.install "restack"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/restack/releases/download/v0.5.4/restack_0.5.4_Darwin_arm64.tar.gz"
      sha256 "d4e2b042a0b2692aa686845f7fe2348a94ed1a23f4ea2ccf8ff7d923c28b4d4f"

      def install
        bin.install "restack"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/restack/releases/download/v0.5.4/restack_0.5.4_Linux_arm64.tar.gz"
      sha256 "bfdf772813a70c4079d8d16fabc301d0649f1f906468e72f44f5ad27fe394d57"

      def install
        bin.install "restack"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/restack/releases/download/v0.5.4/restack_0.5.4_Linux_x86_64.tar.gz"
      sha256 "e96b8e3a735f0771485fe501b2cf14ea2c6639d8fac8372deeedd4c4af093a05"

      def install
        bin.install "restack"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/restack/releases/download/v0.5.4/restack_0.5.4_Linux_armv6.tar.gz"
      sha256 "90448eaadfe643b46c7197c6d2bd08e77d29f365d69da6211d675b3aa552b603"

      def install
        bin.install "restack"
      end
    end
  end

  test do
    system "#{bin}/restack -version"
  end
end
