# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restack < Formula
  desc "Makes interactive Git rebase nicer."
  homepage "https://github.com/abhinav/restack"
  version "0.5.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/restack/releases/download/v0.5.0/restack_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "52fdd3253ba15b65c6a7eb63cebf6de9e4f06341527e2aab0f5d5e64c0752773"
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/restack/releases/download/v0.5.0/restack_0.5.0_Darwin_arm64.tar.gz"
      sha256 "6b52c122487f205f4747a93b697542069ee9324020adea9059f4a86854262a27"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/restack/releases/download/v0.5.0/restack_0.5.0_Linux_x86_64.tar.gz"
      sha256 "3185d9cc93f8306855ddbc4657d8297291b24ab36a223cc12a45e74b1208e7a3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/restack/releases/download/v0.5.0/restack_0.5.0_Linux_arm64.tar.gz"
      sha256 "099649bb607a03831d58a3a7308bca4f8617a98d0cb76785ec7dc7f48bf8b174"
    end
  end

  depends_on "git"

  def install
    bin.install "restack"
  end

  test do
    system "#{bin}/restack -version"
  end
end
