# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stitchmd < Formula
  desc "Stitch multiple Markdown files together into a single document."
  homepage "https://github.com/abhinav/stitchmd"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.2.0/stitchmd-darwin-arm64.tar.gz"
      sha256 "19b51f52e8744cf01b01b63a668078d6aa3253ab04d258e1b2d567857794d891"

      def install
        bin.install "stitchmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.2.0/stitchmd-darwin-amd64.tar.gz"
      sha256 "03e2edc9d23883466f6d0d8b701b4f8f934be6c00d37a7deb0278917369555f4"

      def install
        bin.install "stitchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.2.0/stitchmd-linux-armv6.tar.gz"
      sha256 "ad4263fa15e92ecddacbe784521a989da8d0741674968f6aa32f5d0947bd8837"

      def install
        bin.install "stitchmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.2.0/stitchmd-linux-arm64.tar.gz"
      sha256 "f282619d6f39cfc65e86217c7fb2ef37222d7972c717ec99b482c51a411134e6"

      def install
        bin.install "stitchmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.2.0/stitchmd-linux-amd64.tar.gz"
      sha256 "d942b54fa251415a258e7fcc3daa50eefe09b89af8f4a551b7fda5c0f8285a0d"

      def install
        bin.install "stitchmd"
      end
    end
  end

  test do
    system "#{bin}/stitchmd -version"
  end
end
