# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stitchmd < Formula
  desc "Stitch multiple Markdown files together into a single document."
  homepage "https://github.com/abhinav/stitchmd"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.1.1/stitchmd-darwin-arm64.tar.gz"
      sha256 "254a5124774ed64b4d5d256df12271ccd0a42bc2331bbf7908a9a6ea50097e3f"

      def install
        bin.install "stitchmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.1.1/stitchmd-darwin-amd64.tar.gz"
      sha256 "41172855e5b558ffa0237f26d74c619754414b837556f6e1ac5e3607b5112e1e"

      def install
        bin.install "stitchmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.1.1/stitchmd-linux-arm64.tar.gz"
      sha256 "a52334bba94167e3338d02bc539bd8b250a7c4fd0ca473db01c94f1acac2ef5c"

      def install
        bin.install "stitchmd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.1.1/stitchmd-linux-amd64.tar.gz"
      sha256 "10f623b89462ed6f569033bda8e0b9a56e72eb8a377ab4359285eb85529b0544"

      def install
        bin.install "stitchmd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/stitchmd/releases/download/v0.1.1/stitchmd-linux-armv6.tar.gz"
      sha256 "18c701a7de4ed5e8fcec3d8e8caa48cc736f85c361d84923f748d826b37ab9ee"

      def install
        bin.install "stitchmd"
      end
    end
  end

  test do
    system "#{bin}/stitchmd -version"
  end
end
