# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxFastcopy < Formula
  desc "easymotion-style text copying for tmux."
  homepage "https://github.com/abhinav/tmux-fastcopy"
  version "0.11.1"
  license "GPL-2.0"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.11.1/tmux-fastcopy_0.11.1_Darwin_arm64.tar.gz"
      sha256 "8a6d97c6a15ea72c149702a05321844d7e1806000ef386ece53b137e0709f91a"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.11.1/tmux-fastcopy_0.11.1_Darwin_x86_64.tar.gz"
      sha256 "1bc78d9f64039b66469808e259907bec2adc70b0d13f4d06740d19bec3e722d4"

      def install
        bin.install "tmux-fastcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.11.1/tmux-fastcopy_0.11.1_Linux_armv6.tar.gz"
      sha256 "3c043c4d16b9cdb4bbf741d44108c7dc3d7ebefe186d671fbff0e6896ae182d9"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.11.1/tmux-fastcopy_0.11.1_Linux_arm64.tar.gz"
      sha256 "cd3d154fc38b12be1a822b4c7d4bd124fa0b3aefee368da4a5b00ef23e0690ff"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.11.1/tmux-fastcopy_0.11.1_Linux_x86_64.tar.gz"
      sha256 "ce7edcc36203522cf383bacc02e1a9f1e820f733a81a18bc77baa6ab3bf5bfb7"

      def install
        bin.install "tmux-fastcopy"
      end
    end
  end

  test do
    system "#{bin}/tmux-fastcopy -version"
  end
end
