# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxFastcopy < Formula
  desc "easymotion-style text copying for tmux."
  homepage "https://github.com/abhinav/tmux-fastcopy"
  version "0.13.1"
  license "GPL-2.0"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.13.1/tmux-fastcopy_0.13.1_Darwin_arm64.tar.gz"
      sha256 "8b0c7cc2229e3d76bc4c43f487ea6e1aad35d4a5f6d43a7d7a2a665886aeea39"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.13.1/tmux-fastcopy_0.13.1_Darwin_x86_64.tar.gz"
      sha256 "4b3b125a5d5ce48ca5b9658dbbaaf4112f2e28c5590597d4e8aca5403aa7c4a0"

      def install
        bin.install "tmux-fastcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.13.1/tmux-fastcopy_0.13.1_Linux_armv6.tar.gz"
      sha256 "a737dd5699501ab0357d16ece2fd673824de5bb15d1af9da8bdbf945b3d7b862"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.13.1/tmux-fastcopy_0.13.1_Linux_x86_64.tar.gz"
      sha256 "880737105061b56648cfe31f02ee3df5efbf868ac1d0eb50afc441a075bc9922"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.13.1/tmux-fastcopy_0.13.1_Linux_arm64.tar.gz"
      sha256 "5904f40c824981778cbe3b1f366eef63d4d0bbf0154b395fab200870499d7224"

      def install
        bin.install "tmux-fastcopy"
      end
    end
  end

  test do
    system "#{bin}/tmux-fastcopy -version"
  end
end
