# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxFastcopy < Formula
  desc "easymotion-style text copying for tmux."
  homepage "https://github.com/abhinav/tmux-fastcopy"
  version "0.14.0"
  license "GPL-2.0"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.14.0/tmux-fastcopy_0.14.0_Darwin_x86_64.tar.gz"
      sha256 "55489cf724735267a4fd06317f0718330c78e8ed93065e1e7a65c2f9b06681ae"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.14.0/tmux-fastcopy_0.14.0_Darwin_arm64.tar.gz"
      sha256 "97fa19c934a72d695802d399547bef97d8a489a1384af04575344011442215d5"

      def install
        bin.install "tmux-fastcopy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.14.0/tmux-fastcopy_0.14.0_Linux_armv6.tar.gz"
      sha256 "36aefe97fadc2ceb25a095d1f66c521820d61ceb71bd779f3633daf213f1247e"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.14.0/tmux-fastcopy_0.14.0_Linux_x86_64.tar.gz"
      sha256 "1b61d3cce3a16f9fc9f632466f3fafa676cf390f0c923816a068d1d0cefb1f0e"

      def install
        bin.install "tmux-fastcopy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abhinav/tmux-fastcopy/releases/download/v0.14.0/tmux-fastcopy_0.14.0_Linux_arm64.tar.gz"
      sha256 "944426e92ceb639dc6a9c6563a21fdd2e69fd66813bdeb88bf20b090b2b413f7"

      def install
        bin.install "tmux-fastcopy"
      end
    end
  end

  test do
    system "#{bin}/tmux-fastcopy -version"
  end
end
