# This file was generated by GoReleaser. DO NOT EDIT.
cask "cardamom" do
  version "0.9.5"

  on_macos do
    on_arm do
      sha256 "5305dde486840e2f496b178012e36274cac09978a2b54f252cb69377c8c144fe"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "103973fd386a29e2d26c89c09f9bcfc530e87a978c255e590d3e67c112789f1c"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Darwin-x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2ecbe29b75cad2532f70b882b652767c2478599b79749da4b17d8bf4144e65ec"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Linux-aarch64.tar.gz"
    end
    on_intel do
      sha256 "b83c24c84a3253554d24084ef830b0826ee30aead40175448ffe094acfd4c89a"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Linux-x86_64.tar.gz"
    end
  end

  name "cardamom"
  desc "A local issue tracker for coordinating agent work"
  homepage "https://github.com/abhinav/cardamom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "card"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/card"]
    end
  end

  # No zap stanza required
end
