# This file was generated by GoReleaser. DO NOT EDIT.
cask "cardamom" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "37ede8857937a45d2a4774faf0008cfed69e3df304227347917fbc18613abc38"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Darwin-x86_64.tar.gz"
    end
    on_arm do
      sha256 "b850b3b510abb5c4f6af1faceedb2e068802df905d63b29c5a6f3929c8b38c17"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d55d6f55ff7fb5723a7b5de86433f4d4d6133fa979b0f2bbe18785e451ecec2b"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "67d79886bf1894da65b4ac75a1a6e7a2c8278342d4dc941a738ed5aba894f507"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Linux-aarch64.tar.gz"
    end
  end

  name "cardamom"
  desc "A local issue tracker for coordinating agent work"
  homepage "https://github.com/abhinav/cardamom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "card"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/card"]
    end
  end

  # No zap stanza required

end
