# This file was generated by GoReleaser. DO NOT EDIT.
cask "cardamom" do
  version "0.9.2"

  on_macos do
    on_intel do
      sha256 "6a52e29087054f394a2e5e5008f6d5b0a8b531c04076ca66e2753bf29072ebcb"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Darwin-x86_64.tar.gz"
    end
    on_arm do
      sha256 "569e549862bf63a3cd0a9ce97bbd99fddbf6cdb7790ef5b72dee57ffddb816ac"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d8303d0a804b2c9e5cefd7760802b133cfcf37a3e35ca6c68afbe02903f7a51"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "84c20785da2fca0f318cfc946f3db3c56215b1bde017dc0b15ea8d1123a0e116"
      url "https://github.com/abhinav/cardamom/releases/download/v#{version}/cardamom.Linux-aarch64.tar.gz"
    end
  end

  name "cardamom"
  desc "A local issue tracker for coordinating agent work"
  homepage "https://github.com/abhinav/cardamom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "card"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/card"]
    end
  end

  # No zap stanza required

end
