# This file was generated by GoReleaser. DO NOT EDIT.
cask "doc2go" do
  name "doc2go"
  desc "Your Go documentation, to-go."
  homepage "https://github.com/abhinav/doc2go"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doc2go"

  on_macos do
    on_intel do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-darwin-amd64.tar.gz"
      sha256 "fba92b05f06e746e81b36ff5892946173db282e54da057f14f5d530439faf669"
    end
    on_arm do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-darwin-arm64.tar.gz"
      sha256 "2c59bf383598164ec3154a502a9ec83940aec02289363e2900649c9eabfa1601"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-linux-amd64.tar.gz"
      sha256 "69df6c9bd1702083f9b22cb53b6aa0c50533c8febaa909cd3467cc538649aec0"
    end
    on_arm do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-linux-arm64.tar.gz"
      sha256 "d8e04193e371802b3bb4936194986447f83d5d0bee016f4f04fe8dc41719a4a9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/doc2go"]
    end
  end

  # No zap stanza required
end
