# This file was generated by GoReleaser. DO NOT EDIT.
cask "doc2go" do
  version "0.12.2"

  on_macos do
    on_intel do
      sha256 "cd8dcf59cf16294d1dabf536d711e75d455191bcec9ce633f5a342b8249c827e"
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "d33f93b0d0d3202df860675fec6456e5b62d7b435a1499963e78ab8cf5f4304f"
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29d6206b43ed323f144c91f6e888542c17ae4bb451b2ddfa2e5f7e99e8abccf6"
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "944aed2106ad9abeae3938d941996ae93779434e11219c2788c2f071e2d1c1fc"
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-linux-arm64.tar.gz"
    end
  end

  name "doc2go"
  desc "Your Go documentation, to-go."
  homepage "https://github.com/abhinav/doc2go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doc2go"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/doc2go"]
    end
  end

  # No zap stanza required

end
