# This file was generated by GoReleaser. DO NOT EDIT.
cask "doc2go" do
  name "doc2go"
  desc "Your Go documentation, to-go."
  homepage "https://github.com/abhinav/doc2go"
  version "0.9.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doc2go"

  on_macos do
    on_intel do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-darwin-amd64.tar.gz"
      sha256 "12597beae704089d88022df9c257488f88acb8c811c742da52bb8934184de1da"
    end
    on_arm do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-darwin-arm64.tar.gz"
      sha256 "e7303fb2eb5b9a224fa6621ea146302106b4fe7f7a6cb91a76692a4b6166730c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-linux-amd64.tar.gz"
      sha256 "c0788882c45a06938b9321191dcf72a42c1e0f318e7340695664fdb76742b0d6"
    end
    on_arm do
      url "https://github.com/abhinav/doc2go/releases/download/v#{version}/doc2go-linux-arm64.tar.gz"
      sha256 "9184c2feb732c0e739dfe984b22cdda08fc502071c0bbcb3eec4a09d9cf6f0dc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/doc2go"]
    end
  end

  # No zap stanza required
end
