# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-spice" do
  version "0.30.0"

  on_macos do
    on_intel do
      sha256 "3bec80cd01e793bff7b250f9bceb0ad2b9e6de7db34dcf8096ff3c15f6d897c3"
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Darwin-x86_64.tar.gz"
    end
    on_arm do
      sha256 "0aab6790b04db4bd575d402fc55d4c53074d3b3390035322a3e4127696fdc5c3"
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e5be823f72f264028c88f19cd00202797471d5d8600f281c07c1c1dcaf9920d"
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "1ebe02cd49dfbf6761863a08d85bb3c70a31f11de2598c5a2f87e6bd4d817ce4"
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Linux-aarch64.tar.gz"
    end
  end

  name "git-spice"
  desc "A tool for stacking Git branches."
  homepage "https://abhinav.github.io/git-spice/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-spice"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-spice"]
    end
  end

  # No zap stanza required

end
