# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-spice" do
  name "git-spice"
  desc "A tool for stacking Git branches."
  homepage "https://abhinav.github.io/git-spice/"
  version "0.19.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gs"

  on_macos do
    on_intel do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Darwin-x86_64.tar.gz"
      sha256 "d3649ec7fe6c353e17287c9d3c129cb3b5d6ce83c640ef779d80712a1087b3aa"
    end
    on_arm do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Darwin-arm64.tar.gz"
      sha256 "07ecb51d242d4d14243ee5655632a44361dc9bf2d4667630faec2df0bbb723da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Linux-x86_64.tar.gz"
      sha256 "82f759db438ca5b007850974e643ae68ce3d9065b09629981bfb6216d6fe8096"
    end
    on_arm do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Linux-aarch64.tar.gz"
      sha256 "a5d9d425bd1857d2dd6c143f3ed6404c66d23ae5d7735b15a2f9bfe17489b8a5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gs"]
    end
  end

  # No zap stanza required
end
