# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-spice" do
  name "git-spice"
  desc "A tool for stacking Git branches."
  homepage "https://abhinav.github.io/git-spice/"
  version "0.19.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gs"

  on_macos do
    on_intel do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Darwin-x86_64.tar.gz"
      sha256 "4451ce8981b7ef507ef7b75e5d7e91ccd9c3a52813e6f44f7e8bc8ae73040492"
    end
    on_arm do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Darwin-arm64.tar.gz"
      sha256 "ec0769045ea6fcdbd13e3bfea951b01ed77d309273a373c338d7e7b394a363d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Linux-x86_64.tar.gz"
      sha256 "8c0524b631fe74d126aa31fb5b1edba8fa186294de562a0dcc1ca51ada6f032c"
    end
    on_arm do
      url "https://github.com/abhinav/git-spice/releases/download/v#{version}/git-spice.Linux-aarch64.tar.gz"
      sha256 "2432513c63fc0a37bb088c52a112d721a326d164d6af72b32691dc802f2ac24a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gs"]
    end
  end

  # No zap stanza required
end
