# This file was generated by GoReleaser. DO NOT EDIT.
cask "requiredfield" do
  desc "Go linter that checks for required fields in structs"
  homepage "https://github.com/abhinav/requiredfield"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "requiredfield"

  on_macos do
    on_intel do
      url "https://github.com/abhinav/requiredfield/releases/download/v0.6.1/requiredfield.Darwin-x86_64.tar.gz"
      sha256 "1b553a66ca98f46496e888177b648fb45bc19ded4bacd07b72c3fc738b707aab"
    end
    on_arm do
      url "https://github.com/abhinav/requiredfield/releases/download/v0.6.1/requiredfield.Darwin-arm64.tar.gz"
      sha256 "ad533b3941b4acf82c56772b9c28f8cc89d1ec20da2334866b2fafac889956e8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abhinav/requiredfield/releases/download/v0.6.1/requiredfield.Linux-x86_64.tar.gz"
      sha256 "f3d4222985cb59bbbd1f98f60d3d70afcae54c77f982368b217253bc28f8ec51"
    end
    on_arm do
      url "https://github.com/abhinav/requiredfield/releases/download/v0.6.1/requiredfield.Linux-aarch64.tar.gz"
      sha256 "b0c37f329e0f13609e0dc1540ec7cc497ccedb793ce2a09a2f64f67f4f6a12c3"
    end
  end

  # No zap stanza required
end
