# This file was generated by GoReleaser. DO NOT EDIT.
cask "requiredfield" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "ec9d06e71a947e5676aede10b67d084be177731f8464173b488efe011f474930"
      url "https://github.com/abhinav/requiredfield/releases/download/v#{version}/requiredfield.Darwin-x86_64.tar.gz"
    end
    on_arm do
      sha256 "01918d9178c2b5d8f12a7d2725b5d89fd672ae69112a5210e9dbb54d106f4c73"
      url "https://github.com/abhinav/requiredfield/releases/download/v#{version}/requiredfield.Darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "33cf4d87eb1b540ca3efec4d21a070f750557c638da83e29ffbe84eb48b162de"
      url "https://github.com/abhinav/requiredfield/releases/download/v#{version}/requiredfield.Linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "67963080de1311c9978c865dd16519139af2b92ff235f562ea9ccaefba730f16"
      url "https://github.com/abhinav/requiredfield/releases/download/v#{version}/requiredfield.Linux-aarch64.tar.gz"
    end
  end

  name "requiredfield"
  desc "Go linter that checks for required fields in structs"
  homepage "https://github.com/abhinav/requiredfield"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "requiredfield"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/requiredfield"]
    end
  end

  # No zap stanza required

end
